name: Setup RMCM

on:
  workflow_call:
    outputs:
      cache-hit:
        value: ${{ jobs.rmcm.outputs.cache-hit }}

jobs:
  rmcm:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/rmcm
          key: ${{ runner.os }}-rmcm-v1-${{ hashFiles('.github/workflows/rmcm-install.yml') }}
          restore-keys: ${{ runner.os }}-rmcm-v1-

      - if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/neuxdotdev/comment-remover.git --force

      - run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - run: command -v rmcm && rmcm --version